apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgbouncer.fullname" . }}
data:
  userlist.txt: |
    {{- if .Values.secret.enabled }}
    "pgbouncer" "{{ include "getSecret" (dict "Name" .Values.secret.pgbouncer.name "Key" .Values.secret.pgbouncer.key) }}"
    {{- else }}
    "pgbouncer" "pgbouncer"
    {{- end }}