apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgbouncer.fullname" . }}
data:
  userlist.txt: |
    {{- if gt (len .Values.pgbouncerAuth) 0 }}
      {{- range $auth := .Values.pgbouncerAuth }}
        {{- if $auth.secret }}
          {{- printf "\n\"%s\"" $auth.username | indent 4 }} "{{ include "getSecret" (dict "Name" $auth.secret.name "Key" $auth.secret.key) }}"
        {{- else }}
          {{- printf "\n\"%s\"" $auth.username | indent 4 }} "{{ $auth.password }}"
        {{- end }}
      {{- end }}
    {{- else }}
    "pgbouncer" "pgbouncer"
    {{- end }}