apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
{{ include "pgbouncer.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pgbouncer.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pgbouncer.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "pgbouncer.serviceAccountName" . }}
      volumes:
        - name: config-volume
          configMap:
            name: user-list
{{/*            items:*/}}
{{/*              - key: userlist.txt*/}}
{{/*                path: userlist.txt*/}}
{{/*                mode: 0777*/}}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          {{- range $k, $v := .Values.bitnami }}
            - name: {{ $k | quote }}
              value: {{ $v | quote }}
          {{- end }}
            - name: PGBOUNCER_USERLIST
              value: '"{{ .Values.bitnami.PGBOUNCER_AUTH_USER }}" "{{ include "getSecret" (dict "Name" "reyield" "Key" "db-password") }}"'
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reyield
                  key: db-password
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: pgbouncer
              containerPort: {{ .Values.pgbouncer.port }}
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /opt/pgbouncer/conf
          readinessProbe:
            tcpSocket:
              port: {{ .Values.pgbouncer.port }}
          lifecycle:
            preStop:
              exec:
                # https://freecontent.manning.com/handling-client-requests-properly-with-kubernetes/
                command: ["/bin/sh", "-c", "sleep 5"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
