apiVersion: v1
appVersion: 1.15.0
description: Lightweight connection pooler for PostgreSQL
home: http://www.pgbouncer.org
icon: https://raw.githubusercontent.com/belaytzev/pgbouncer-helm/main/pgbouncer.png
keywords:
- pgbouncer
- postgres
- database
- sql
maintainers:
- name: belaytzev
name: pgbouncer
version: 1.15.1
