replicaCount: 1

image:
  repository: bitnami/pgbouncer
  tag: 1.19.0
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}

serviceAccount:
  create: false

securityContext: {}

service:
  type: ClusterIP
  port: 6432

ingress:
  enabled: false
  annotations: {}

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

## Specify existing secret
secret:
  pgbouncer:
    name: ""
    key: ""
  postgres:
    name: ""
    key: ""

env:
  ##  Backend PostgreSQL connection
  POSTGRESQL_USERNAME: postgres
  POSTGRESQL_PASSWORD: postgres
  POSTGRESQL_DATABASE: postgres
  POSTGRESQL_HOST: ""
  POSTGRESQL_PORT: 5432
  PGBOUNCER_SET_DATABASE_USER: yes
  PGBOUNCER_SET_DATABASE_PASSWORD: yes
  PGBOUNCER_CONNECT_QUERY: ""
  ## PgBouncer
  PGBOUNCER_AUTH_TYPE: plain
  ## Port and address binding
  PGBOUNCER_PORT: 6432
  PGBOUNCER_BIND_ADDRESS: 0.0.0.0
  ## Extra arguments to PgBouncer startup
  PGBOUNCER_EXTRA_FLAGS: ""
  ## Exposed database
  PGBOUNCER_DATABASE: postgres
  ## Options
  PGBOUNCER_AUTH_USER: "pgbouncer"
  PGBOUNCER_AUTH_QUERY: ""
  PGBOUNCER_USERLIST: '"pgbouncer" "pgbouncer"'
  PGBOUNCER_POOL_MODE: transaction
  PGBOUNCER_INIT_SLEEP_TIME: 10
  PGBOUNCER_INIT_MAX_RETRIES: 10
  PGBOUNCER_QUERY_WAIT_TIMEOUT: 120
  PGBOUNCER_MAX_CLIENT_CONN: 120
  PGBOUNCER_MAX_DB_CONNECTIONS: 0
  PGBOUNCER_IDLE_TRANSACTION_TIMEOUT: 0.0
  PGBOUNCER_DEFAULT_POOL_SIZE: 50
  PGBOUNCER_MIN_POOL_SIZE: 0
  PGBOUNCER_RESERVE_POOL_SIZE: 0
  PGBOUNCER_IGNORE_STARTUP_PARAMETERS: ""
  PGBOUNCER_SERVER_IDLE_TIMEOUT: 600
  PGBOUNCER_SERVER_RESET_QUERY: DISCARD ALL
  PGBOUNCER_STATS_USERS: ""
  ## Securing PgBouncer traffic
  PGBOUNCER_CLIENT_TLS_SSLMODE: disable
  PGBOUNCER_CLIENT_TLS_CERT_FILE: ""
  PGBOUNCER_CLIENT_TLS_KEY_FILE: ""
  PGBOUNCER_CLIENT_TLS_CA_FILE: ""
  PGBOUNCER_CLIENT_TLS_CIPHERS: fast
  PGBOUNCER_SERVER_TLS_SSLMODE: disable
  PGBOUNCER_SERVER_TLS_KEY_FILE: ""
  PGBOUNCER_SERVER_TLS_CERT_FILE: ""
  PGBOUNCER_SERVER_TLS_CA_FILE: ""
  PGBOUNCER_SERVER_TLS_PROTOCOLS: secure
  PGBOUNCER_SERVER_TLS_CIPHERS: fast
